### ISSUE TITLE
add a LICENSE file

### ISSUE THREAD

**Issue by stephenturner** [KHanghoj/NGSremix#2]
Just saw the G3 publication, looking forward to trying this out. I see the R pkg DESCRIPTION notes GPL, and several refs to GPL throughout other bits of the code. I suggest adding a LICENSE file in the root of the repository to make this more apparent.

**Comment by KHanghoj** [comment]
Thanks for noting. The LICENSE has been added. commit: 626063a786b045490bd977e3b3e2836786ad5186
