### ISSUE TITLE
Problem: "Only X sites in frequency file (maybe increase buffer)"

### ISSUE THREAD

**Issue by carlos-sarabia** [KHanghoj/NGSremix#3]
Hi, 

Thanks for providing with such an easy-to-use and useful program. After installing it correctly and testing it on the test_data, I am experiencing an issue. 

I have two populations, one with 10 and another with 23 individuals. I want to see if I have kinship relationships within them. Independently on what K I had during the NGSadmix run, NGSremix pulls the same problem:

"Only X sites in frequency file (maybe increase buffer)"

I used first a small chromosome with the largest population:

```
NGSremix -beagle 0.beagle.input/chr38.turkey.filtered.beagle.gz -qname 1.NGSadmix.results/chr38.turkey.K4.rep1.run.qopt -fname 1.NGSadmix.results/chr38.turkey.K4.rep1.run.fopt.gz -seed 1 -o test.chr38/res.turkey.4 -P 1 
	-> Seed is: 1
	-> Beagle - Reading from: 0.beagle.input/chr38.turkey.filtered.beagle.gz
	-> Beagle - 82976 sites and 23 nInd processed
	-> Beagle - Transpose from 82976 X 23*3 to 23 X 82976*3
	-> K=4	nSites=82976	nInd=23
	-> Opening : 1.NGSadmix.results/chr38.turkey.K4.rep1.run.fopt.gz with x=82976 y=4
Error: Only 24386 sites in frequency file (maybe increase buffer)
```

Then the same with the small population, which had 110549 sites in that chromosome. Using the largest chromosome chr01:

`NGSremix -beagle chr01.israel.filtered.beagle.gz -qname chr01.israel.K3.rep1.run.qopt -fname chr01.israel.K3.rep1.run.fopt.gz -seed 1 -o test.chr38/chr01.res.israel.3 -P 1 
	-> Seed is: 1
	-> Beagle - Reading from: 0.beagle.input/chr01.israel.filtered.beagle.gz
	-> Beagle - 429744 sites and 10 nInd processed
	-> Beagle - Transpose from 429744 X 10*3 to 10 X 429744*3
	-> K=3	nSites=429744	nInd=10
	-> Opening : 1.NGSadmix.results/chr01.israel.K3.rep1.run.fopt.gz with x=429744 y=3
Error: Only 409326 sites in frequency file (maybe increase buffer)
4
`

What intrigues me is, the provided test data have 10K sites and works well:

`../src/NGSremix -beagle test.beagle.gz -qname test.3.qopt -fname test.3.fopt.gz -seed 1 -o res -P 1 
	-> Seed is: 1
	-> Beagle - Reading from: test.beagle.gz
	-> Beagle - 10000 sites and 6 nInd processed
	-> Beagle - Transpose from 10000 X 6*3 to 6 X 10000*3
	-> K=3	nSites=10000	nInd=6
	-> Opening : test.3.fopt.gz with x=10000 y=3
	-> Calculating paired ancestry coefficients. Dumping to res.pairedanc
	-> 0/6 paired ancestries estimated
	-> 6 paired ancestry estimates took 0 sec.
	-> running i1:4 i2:5
	[ALL done] cpu-time used =  3.50 sec
	[ALL done] walltime used =  4.00 sec
	[ALL done] results have been outputted to res
res: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
`
Even if it says "FAILED" for res and throws a warning, the output file looks correct:

`$ head res
ind1	ind2	k0	k1	k2	nIter
1	2	0.017304	0.982693	0.000003	26
1	3	0.999007	0.000497	0.000496	1
1	4	0.999012	0.000496	0.000491	1
1	5	0.999003	0.000498	0.000499	1
1	6	0.997590	0.000002	0.002408	29
2	3	0.998298	0.000004	0.001699	26
`
The single clue about this error message is in function void readDoubleGZ from the Cinterface.cpp file, which says:

`void readDoubleGZ(double **d,int x,int y,const char*fname,int neg){
  fprintf(stdout,"\t-> Opening : %s with x=%d y=%d\n",fname,x,y);
  const char*delims=" \n";
  gzFile fp = NULL;
  
  [...]
int lens=1000000 ;
char buf[lens];
for(int i=0;i<x;i++){
    if(NULL==gzgets(fp,buf,lens)){
 	fprintf(stderr,"Error: Only %d sites in frequency file (maybe increase buffer)\n",i);
	exit(0);
    }  
  `

Does it have anything to do with the lens number? Why does it not work with my chromosome 1 with 409326 sites if it works with the test data provided with 10000 sites? How can I increase the buffer as suggested, was it in the step of NGSadmix or NGSremix?

Best regards and thanks!

**Comment by KHanghoj** [comment]
Hi,

The error message is inaccurate. I am pretty sure the issue is ngsadmix. It quietly excludes sites with MAF < 0.05. I have made a small c++ software to remove MAF<0.05 sites from your beagle file using the same algorithm as NGSadmix. see here: https://github.com/KHanghoj/maf_beagle_ngsadmix

The makefile has an example on how to run it. 

Alternatively, use `-printInfo` when you run ngsadmix. It should show the sites excluded from the admixture analyses. 

Let me know if it doesnt work. 

Kristian

**Comment by carlos-sarabia** [comment]
Dear @KHanghoj , 

Thanks for your swift response and the provided software! In fact, you were right. Beagle had considered the maf<0.05 filter and the fopt file had a number of rows less than the beagle.gz file. 

After removing the sites with maf<0.05 using your software, I ran again NGSremix and it worked very well:
```

[more test.chr38/res.turkey.K4
ind1	ind2	k0	k1	k2	nIter
1	2	0.236626	0.000000	0.763374	20
1	3	0.999013	0.000496	0.000492	1
1	4	1.000000	0.000000	0.000000	1
1	5	1.000000	0.000000	0.000000	1
1	6	0.999007	0.000499	0.000494	1
1	7	1.000000	0.000000	0.000000	1

```
 
One thing I tried, and that might be an important piece of information for other users: setting NGSadmix with -minmaf 0 and trying to throw all sites into the .fopt.gz and .qopt files to later run NGSremix does not work and I think it is related to the estimation of log-likelihoods for K. 

```
more test.chr38/res.turkey.4
ind1	ind2	k0	k1	k2	nIter
1	2	-nan	-nan	-nan	4999
1	3	-nan	-nan	-nan	4999
1	4	-nan	-nan	-nan	4999
1	5	-nan	-nan	-nan	4999
1	6	-nan	-nan	-nan	4999
1	7	-nan	-nan	-nan	4999
1	8	-nan	-nan	-nan	4999
```

Thanks!

**Comment by KHanghoj** [comment]
I think the likelihood is not handling sites that arent polymorphic. 

Ill will add a warning in the program to make the end-user aware of this.

We do not recommend to run the program without a maf filter.  

Let me know if you have any other questions.

**Comment by KHanghoj** [comment]
by the way. can you send an example where it crashes with minmaf=0. Ill add a warning in ngsREMIX
